#!/usr/bin/env bash
#-*- mode: shell-script; coding: utf-8; -*-

tar="${TAR:-tar}"

NENV_VERSION="0.0.9"
export NENV_VERSION
NODE_LOCAL_VERSION_FILE=".nenv-version"
export NODE_LOCAL_VERSION_FILE

git_url="https://github.com/joyent/node.git"

resolve_link(){
    $(type -p greadlink readlink | head -1) $1
}

absolute_dirname(){
    local cwd="$(pwd)"
    local path="$1"

    while [ -n "$path" ]; do
        cd "${path%/*}"
        local name="${path##*/}"
        path="$(resolve_link "$name" || true)"
    done

    pwd
    cd "$cwd"
}

expand_path(){
    if [ ! -d "$1" ]; then
        return 1
    fi

    local cwd="$(pwd)"
    cd "$1"
    pwd
    cd "$cwd"
}

remove_from_path(){
    local path_to_remove="$(expand_path "$1")"
    local result=""

    if [ -z "$path_to_remove" ]; then
        echo "${PATH}"
        return
    fi

    for path in ${PATH//:/$'\n'}; do
        path="$(expand_path "$path" || true)"
        if [ -n "$path" ] && [ "$path" != "$path_to_remove" ]; then
            result="${result}${path}:"
        fi
    done

    echo "${result%:}"
}

parse_options(){
    OPTIONS=();
    ARGUMENTS=();
    local arg;
    for arg in "$@";
    do
        if [ "${arg:0:1}" = "-" ]; then
            if [ "${arg:1:1}" = "-" ]; then
                OPTIONS[${#OPTIONS[*]}]="${arg:2}";
            else
                if [ ${#arg} -gt 2 ]; then
                    echo "Option is wrong \"$arg\"";
                    exit 1;
                fi;
                OPTIONS[${#OPTIONS[*]}]="${arg:1}"
            fi;
        else
            ARGUMENTS[${#ARGUMENTS[*]}]="$arg";
        fi;
    done
}
