#!/usr/bin/env bash
#-*- mode: shell-script; coding: utf-8; -*-

tar="${TAR:-tar}"

NENV_VERSION="0.0.5"
export NENV_VERSION
NODE_LOCAL_VERSION_FILE=".nenv-version"
export NODE_LOCAL_VERSION_FILE

git_url="https://github.com/joyent/node.git"

nenv_version(){
    echo $NENV_VERSION
}

resolve_link() {
    $(type -p greadlink readlink | head -1) $1
}

absolute_dirname() {
    local cwd="$(pwd)"
    local path="$1"

    while [ -n "$path" ]; do
        cd "${path%/*}"
        local name="${path##*/}"
        path="$(resolve_link "$name" || true)"
    done

    pwd
    cd "$cwd"
}

expand_path() {
    if [ ! -d "$1" ]; then
        return 1
    fi

    local cwd="$(pwd)"
    cd "$1"
    pwd
    cd "$cwd"
}

remove_from_path() {
    local path_to_remove="$(expand_path "$1")"
    local result=""

    if [ -z "$path_to_remove" ]; then
        echo "${PATH}"
        return
    fi

    for path in ${PATH//:/$'\n'}; do
        path="$(expand_path "$path" || true)"
        if [ -n "$path" ] && [ "$path" != "$path_to_remove" ]; then
            result="${result}${path}:"
        fi
    done

    echo "${result%:}"
}
