#!/usr/bin/env bash
#-*- mode: shell-script; coding: utf-8; -*-

tar="${TAR:-tar}"

NENV_VERSION="0.0.9"
export NENV_VERSION
NODE_LOCAL_VERSION_FILE=".nenv-version"
export NODE_LOCAL_VERSION_FILE

git_url="https://github.com/joyent/node.git"

resolve_link(){
    $(type -p greadlink readlink | head -1) $1
}

absolute_dirname(){
    local cwd="$(pwd)"
    local path="$1"

    while [ -n "$path" ]; do
        cd "${path%/*}"
        local name="${path##*/}"
        path="$(resolve_link "$name" || true)"
    done

    pwd
    cd "$cwd"
}

parse_options(){
    OPTIONS=();
    ARGUMENTS=();
    local arg;
    for arg in "$@";
    do
        if [ "${arg:0:1}" = "-" ]; then
            if [ "${arg:1:1}" = "-" ]; then
                OPTIONS[${#OPTIONS[*]}]="${arg:2}";
            else
                if [ ${#arg} -gt 2 ]; then
                    echo "Option is wrong \"$arg\"";
                    exit 1;
                fi;
                OPTIONS[${#OPTIONS[*]}]="${arg:1}"
            fi;
        else
            ARGUMENTS[${#ARGUMENTS[*]}]="$arg";
        fi;
    done
}
