#!/usr/bin/env bash
# Summary: List all Node versions that contain the given executable
# Usage: nenv whence [--path] <command>

set -e
[ -n "$NENV_DEBUG" ] && set -x

# Provide nenv completions
if [ "$1" = "--complete" ]; then
  echo --path
  exec nenv shims --short
fi

if [ "$1" = "--path" ]; then
  print_paths="1"
  shift
else
  print_paths=""
fi

whence() {
  local command="$1"
  nenv-versions --bare | while read version; do
    path="$(nenv-prefix "$version")/bin/${command}"
    if [ -x "$path" ]; then
      [ "$print_paths" ] && echo "$path" || echo "$version"
    fi
  done
}

NENV_COMMAND="$1"
if [ -z "$NENV_COMMAND" ]; then
  nenv-help --usage whence >&2
  exit 1
fi

result="$(whence "$NENV_COMMAND")"
[ -n "$result" ] && echo "$result"
