#!/usr/bin/env bash
#-*- mode: shell-script; coding: utf-8; -*-

set -e
[[ -n $NENV_DEBUG ]] && set -x

NODE_VERSION="$1"
case "$NODE_VERSION" in
    "" | "-h" | "--help" )
        echo "usage: nenv "${0/*nenv-/}" NODE_VERSION" >&2
        exit 1
        ;;
    --command-help )
        nenv versions --bare
        ;;
    * )
        NENV_PREFIX_PATH="${NENV_ROOT}/versions/${NODE_VERSION}"

        if [ ! -d "$NENV_PREFIX_PATH" ]; then
            echo "nenv: version '${NODE_VERSION}' not installed" >&2
            exit 1
        fi

        rm -rf "$NENV_PREFIX_PATH"

        nenv-rehash
        ;;
esac
