#!/usr/bin/env bash
#-*- mode: shell-script; coding: utf-8; -*-
set -e
[[ -n $NENV_DEBUG ]] && set -x

case "$1" in
    "-h" | "--help" )
        echo "usage: nenv "${0/*nenv-/}"" >&2
        exit 1
        ;;
    --command-help )
        exit;
        ;;
    * )
        echo "$(nenv-version-name) (set by $(nenv-version-obtain-from))"
        ;;
esac
