#!/usr/bin/env bash
#-*- mode: shell-script; coding: utf-8; -*-
set -e
[[ -n $NENV_DEBUG ]] && set -x

case "$1" in
    "-h" | "--help" )
        echo "usage: nenv "${0/*nenv-/}" [--short]" >&2
        exit 1
        ;;
    --command-help )
        echo "--short"
        exit;
        ;;
    * )
        for command in "${NENV_ROOT}/shims/"*; do
            if [ "$1" = "--short" ]; then
                echo "${command##*/}"
            else
                echo "$command"
            fi
        done | sort
        ;;
esac
