#!/usr/bin/env bash
#-*- mode: shell-script; coding: utf-8; -*-

set -e
[[ -n $NENV_DEBUG ]] && set -x

NENV_VERSION="$1"

if [ -z "$NENV_VERSION" ]; then
    echo "usage: nenv "${0/*nenv-/}" VERSION" >&2
    exit 1
fi

NENV_PREFIX_PATH="${NENV_ROOT}/versions/${NENV_VERSION}"

if [ ! -d "$NENV_PREFIX_PATH" ]; then
    echo "nenv: version '${NENV_VERSION}' not installed" >&2
    exit 1
fi

rm -rf "$NENV_PREFIX_PATH"

nenv-rehash
