#!/usr/bin/env bash
# Summary: Show the current Node version and its origin
#
# Shows the currently selected Node version and how it was
# selected. To obtain only the version string, use `nenv
# version-name'.

set -e
[ -n "$NENV_DEBUG" ] && set -x

echo "$(nenv-version-name) (set by $(nenv-version-origin))"
