#!/usr/bin/env bash
#
# Summary: Install a Node version from git
#
# Usage: nenv install [-f] [-vps] <version>
#        nenv install [-f] [-vps] <definition-file>
#        nenv install -l|--list
#
#   -l/--list          List all available versions
#   -f/--force         Install even if the version appears to be installed already
#   -s/--skip-existing Skip if the version appears to be installed already
#   -v/--verbose       Verbose mode: print compliation status to stdout
#   -p/--patch         Apply a patch from stdin before building

set -e
[[ -n $NENV_DEBUG ]] && set -x

source "${NENV_ROOT}/lib/nenv-functions"

NODE_BUILD_ROOT="$(absolute_dirname "$0")/.."

nenv_installed(){
    local version="$1"
    [ -d "$NENV_ROOT/versions/$version/bin" ] || return 1
}

nenv_remote_versions() {
    curl -so - -L -4 https://iojs.org/dist/index.tab \
      | cut -f 1 | tail -n +2 \
    && \
    curl -so - -L -4 https://nodejs.org/dist/ \
       | egrep '<a href="v.*/'          \
       | egrep -o '"v[^"]+/'            \
       | tr -d \"/                      \
       | egrep -o '[^v]+'               \
       | sort -V
}

nenv_get_kernel_name(){
  local kernel_name=`uname -s`

  case "$kernel_name" in
    "Linux")
      kernel_type="-linux"
      ;;
    "Darwin")
      kernel_type="-darwin"
      ;;
  esac
  echo $kernel_type
}

nenv_get_arch_name(){
  local arch_name=`uname -m`

  case "$arch_name" in
    "x86_64")
      arch_type="-x64"
      ;;
    "i686")
      arch_type="-x86"
      ;;
  esac
  echo $arch_type

}

nenv_get_file_name(){
  local version="$1"
  local node_binary_install="$2"
  local kernel_type="$(nenv_get_kernel_name)"
  local arch_type="$(nenv_get_arch_name)"

  case "$node_binary_install" in
    "true")
      file_name="node-v${version}${kernel_type}${arch_type}.tar.gz"
      ;;
    *)
      file_name="node-v${version}.tar.gz"
      ;;
  esac
  echo $file_name
}

nenv_fetch_tarball(){
    local version="$1"
    local node_binary_install="$2"
    local file_name="$(nenv_get_file_name "$version" "$node_binary_install")"
    local url="http://nodejs.org/dist/v${version}/${file_name}"

    echo "Now getting tarball. Version : ${version}" >&4 2>&1
    pushd "$TEMP_PATH" >&4
    {
        curl -# -L -4 "$url" | $tar zxf - -C "." --strip-components=1
    } >&4 2>&1
    popd >&4
}

nenv_fetch_git(){
    local branch="$1"

    echo "Create git directory : ${NENV_SOURCE_PATH}" >&4 2>&1
    mkdir -p "$NENV_SOURCE_PATH"
    pushd "$NENV_SOURCE_PATH" >&4

    if [ -d "$NENV_SOURCE_PATH/${branch}" ]; then
        echo "Pulling ${git_url}..." >&2
        pushd "$NENV_SOURCE_PATH/${branch}" >&4
        {
            git pull
        } >&4 2>&1
        popd >&4
    else
        echo "Cloning ${git_url}..." >&2
        {
            git clone --depth 1 --branch "${branch}" "${git_url}" "${branch}"
        } >&4 2>&1
    fi
    popd >&4
}

nenv_make_package_tarball(){
    local version="$1"

    echo "Compiling..." >&4 2>&1
    pushd "$TEMP_PATH" >&4
    {
        ./configure --prefix=$PREFIX_PATH $CONFIGURE_OPTS
        make
        make install
    } >&4 2>&1
    popd >&4
}

nenv_make_package_git(){
    local version="$1"

    echo "Compiling..." >&4 2>&1
    pushd "$NENV_SOURCE_PATH/${version}" >&4
    {
        ./configure --prefix=$PREFIX_PATH $CONFIGURE_OPTS
        make
        ./tools/waf-light install
    } >&4 2>&1
    popd >&4

}

nenv_install_from(){
    local install_type="$1"
    local node_version="$2"
    local node_binary_install="$3"
    shift 3

    if nenv_installed "$node_version"; then
        echo "Already installed: $node_version" >&2
        return 0
    fi
    echo "Open log file to ${LOG_PATH}" >&2
    exec 4<> "$LOG_PATH"
    if [ -n "$VERBOSE" ]; then
        tail -f "$LOG_PATH" &
        trap "kill 0" SIGINT SIGTERM EXIT
    fi

    echo "Create temp directory. : ${TEMP_PATH}" >&4 2>&1
    mkdir -p "$TEMP_PATH"
    "nenv_fetch_${install_type}" "$node_version" $node_binary_install $*

    case "$node_binary_install" in
      "true")
        nenv_move_node_binary_module "$node_version"
        ;;
      *)
        "nenv_make_package_${install_type}" "$node_version" $*
        ;;
    esac

    echo "Remove temp directory. : ${TEMP_PATH}" >&4 2>&1
    rm -rf "$TEMP_PATH"
    nenv-rehash
    return 0
}

nenv_move_node_binary_module(){
    local version="$1"

    echo "Moving... node module." >&4 2>&1
    pushd "$TEMP_PATH" >&4
    {
        mkdir -p $PREFIX_PATH
        mv ./* $PREFIX_PATH/
    } >&4 2>&1
    popd >&4
}

nenv_install_package(){
    nenv_install_from "tarball" $*
}

nenv_install_git(){
    nenv_install_from "git" $*
}

usage(){
    {
        nenv---version
        echo "usage: nenv "${0/*nenv-/}" [--verbose] [--debug] [--gdb] VERSION"
    } >&2
}

if [ -z "$TMPDIR" ]; then
    TMP="/tmp"
else
    TMP="${TMPDIR%/}"
fi

parse_options "$@"
unset NODE_VERSION
unset VERBOSE
unset CONFIGURE_OPTS
NODE_BINARY_INSTALL=false

for argument in "${ARGUMENTS[@]}"; do
    case "$argument" in
        "git")
            {
                # nenv_install_git "master"
                echo "Does not support yet." >&2
                exit 0
            }
            ;;
        "binary")
            NODE_BINARY_INSTALL=true
            ;;
        *)
            NODE_VERSION="$argument"
            ;;
    esac
done

for option in "${OPTIONS[@]}"; do
    case "$option" in
        "h" | "help" )
            usage
            exit;
            ;;
        "l" | "list" )
            echo "Available versions"
            nenv_remote_versions
            exit;
            ;;
        "verbose" )
            echo "verbose enable"
            VERBOSE=true
            ;;
        "debug" )
            echo "debug enable"
            CONFIGURE_OPTS="${CONFIGURE_OPTS} --debug "
            ;;
        "gdb" )
            echo "gdb enable"
            CONFIGURE_OPTS="${CONFIGURE_OPTS} --gdb "
            ;;
    esac
done

if [ ${#ARGUMENTS[*]} -eq 0 ]; then
    usage
    exit;
fi;

SEED="$(date "+%Y%m%d%H%M%S").$$"
LOG_PATH="${TMP}/node-build.${SEED}.log"
TEMP_PATH="${TMP}/node-build.${SEED}"
PREFIX_PATH="${NENV_ROOT}/versions/${NODE_VERSION}"
NENV_SOURCE_PATH="${NENV_ROOT}/sources"

nenv_install_package $NODE_VERSION $NODE_BINARY_INSTALL ${OPTIONS[*]}
