#!/usr/bin/env bash
#-*- mode: shell-script; coding: utf-8; -*-
set -e
[[ -n $NENV_DEBUG ]] && set -x

case "$1" in
    "-h" | "--help" )
        echo "usage: nenv "${0/*nenv-/}"" >&2
        exit 1
        ;;
    --command-help )
        exit;
        ;;
    * )
        if [ -n "$NODE_VERSION" ]; then
            echo "NODE_VERSION environment variable"
        else
            nenv-version-file "file"
        fi
        ;;
esac
