#!/usr/bin/env bash
set -e
export -n CDPATH

if [ "$1" = "--debug" ]; then
  export NENV_DEBUG=1
  shift
fi

if [ -n "$NENV_DEBUG" ]; then
  export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] '
  set -x
fi

READLINK=$(type -p greadlink readlink | head -1)
if [ -z "$READLINK" ]; then
  echo "nenv: cannot find readlink - are you missing GNU coreutils?" >&2
  exit 1
fi

resolve_link() {
  $READLINK "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

if [ -z "${NENV_ROOT}" ]; then
  NENV_ROOT="${HOME}/.nenv"
else
  NENV_ROOT="${NENV_ROOT%/}"
fi
export NENV_ROOT

if [ -z "${NENV_DIR}" ]; then
  NENV_DIR="$(pwd)"
else
  cd "$NENV_DIR" 2>/dev/null || {
    echo "nenv: cannot change working directory to \`$NENV_DIR'"
    exit 1
  } >&2
  NENV_DIR="$(pwd)"
  cd "$OLDPWD"
fi
export NENV_DIR


shopt -s nullglob

bin_path="$(abs_dirname "$0")"
for plugin_bin in "${NENV_ROOT}/plugins/"*/bin; do
  bin_path="${bin_path}:${plugin_bin}"
done
export PATH="${bin_path}:${PATH}"

hook_path="${NENV_HOOK_PATH}:${NENV_ROOT}/nenv.d:/usr/local/etc/nenv.d:/etc/nenv.d:/usr/lib/nenv/hooks"
for plugin_hook in "${NENV_ROOT}/plugins/"*/etc/nenv.d; do
  hook_path="${hook_path}:${plugin_hook}"
done
export NENV_HOOK_PATH="$hook_path"

shopt -u nullglob


command="$1"
case "$command" in
"" | "-h" | "--help" )
  echo -e "$(nenv---version)\n$(nenv-help)" >&2
  ;;
"-v" )
  exec nenv---version
  ;;
* )
  command_path="$(command -v "nenv-$command" || true)"
  if [ -z "$command_path" ]; then
    echo "nenv: no such command \`$command'" >&2
    exit 1
  fi

  shift 1
  exec "$command_path" "$@"
  ;;
esac
