#!/usr/bin/env bash
#-*- mode: shell-script; coding: utf-8; -*-
set -e
[[ -n $NENV_DEBUG ]] && set -x

if [ -n "$NODE_VERSION" ]; then
    echo "NODE_VERSION environment variable"
else
    nenv-version-file "file"
fi
