#!/usr/bin/env bash
# Summary: Detect the file that sets the current nenv version
set -e
[ -n "$NENV_DEBUG" ] && set -x

find_local_version_file() {
  local root="$1"
  while [ -n "$root" ]; do
    if [ -e "${root}/.node-version" ]; then
      echo "${root}/.node-version"
      exit
    elif [ -e "${root}/.nenv-version" ]; then
      echo "${root}/.nenv-version"
      exit
    fi
    root="${root%/*}"
  done
}

find_local_version_file "$NENV_DIR"
[ "$NENV_DIR" = "$PWD" ] || find_local_version_file "$PWD"

global_version_file="${NENV_ROOT}/version"

if [ -e "$global_version_file" ]; then
  echo "$global_version_file"
elif [ -e "${NENV_ROOT}/global" ]; then
  echo "${NENV_ROOT}/global"
elif [ -e "${NENV_ROOT}/default" ]; then
  echo "${NENV_ROOT}/default"
else
  echo "$global_version_file"
fi
