#!/usr/bin/env bash
#-*- mode: shell-script; coding: utf-8; -*-

set -e
[[ -n $NENV_DEBUG ]] && set -x

case "$1" in
    "" )
        echo " nenv --help COMMAND"
        ;;
    --command-help )
        commands=($(command ls ${NENV_ROOT}/libexec/nenv-*))
        echo ${commands[*]##*nenv-}
        ;;
    * )
        command_path="$(command -v "nenv-$1" || true)"
        echo $command_path
        if [ -n "$command_path" ]; then
            echo "Sorry, the \`$1' command's document is not prepared."
            echo ""
            echo "command is here:"
            echo "  $command_path"
            echo ""
        else
            echo "nenv: no command \`$1'"
        fi
esac
