#!/usr/bin/env bash
#
# Summary: Uninstall a specific Node version
#
# Usage: nenv uninstall [-f|--force] <version>
#
#    -f  Attempt to remove the specified version without prompting
#        for confirmation. If the version does not exist, do not
#        display an error message.
#
# See `nenv versions` for a complete list of installed versions.
#
set -e

# Provide nenv completions
if [ "$1" = "--complete" ]; then
  exec nenv versions --bare
fi

if [ -z "$NENV_ROOT" ]; then
  NENV_ROOT="${HOME}/.nenv"
fi

unset FORCE
if [ "$1" = "-f" ] || [ "$1" = "--force" ]; then
  FORCE=true
  shift
fi

DEFINITION="$1"
case "$DEFINITION" in
"" | -* )
  # We can remove the sed fallback once nenv 0.4.0 is widely available.
  { nenv-help uninstall 2>/dev/null ||
    sed -ne '/^#/!q;s/.\{1,2\}//;1,4d;p' < "$0"
  } >&2
  exit 1
  ;;
esac

declare -a before_hooks after_hooks

before_uninstall() {
  local hook="$1"
  before_hooks["${#before_hooks[@]}"]="$hook"
}

after_uninstall() {
  local hook="$1"
  after_hooks["${#after_hooks[@]}"]="$hook"
}

OLDIFS="$IFS"
IFS=$'\n' scripts=(`nenv-hooks uninstall`)
IFS="$OLDIFS"
for script in "${scripts[@]}"; do source "$script"; done


VERSION_NAME="${DEFINITION##*/}"
PREFIX="${NENV_ROOT}/versions/${VERSION_NAME}"

if [ -z "$FORCE" ]; then
  if [ ! -d "$PREFIX" ]; then
    echo "nenv: version \`$VERSION_NAME' not installed" >&2
    exit 1
  fi

  read -p "nenv: remove $PREFIX? "
  case "$REPLY" in
  y* | Y* ) ;;
  * ) exit 1 ;;
  esac
fi

for hook in "${before_hooks[@]}"; do eval "$hook"; done

if [ -d "$PREFIX" ]; then
  rm -rf "$PREFIX"
  nenv-rehash
fi

for hook in "${after_hooks[@]}"; do eval "$hook"; done
