#!/usr/bin/env bash
#-*- mode: shell-script; coding: utf-8; -*-

set -e
[[ -n $NENV_DEBUG ]] && set -x

command_path="$(command -v "nenv-$1" || true)"
if [ -n "$command_path" ]; then
    echo "Sorry, the \`$1' command's document is not prepared."
    echo ""
    echo "command is here:"
    echo "  $command_path"
    echo ""
else
    echo "nenv: no command \`$1'"
fi
