#!/usr/bin/env bash
#-*- mode: shell-script; coding: utf-8; -*-
set -e
[[ -n $NENV_DEBUG ]] && set -x

if [ -n "$1" ]; then
    export NODE_VERSION="$1"
elif [ -z "$NODE_VERSION" ]; then
    NODE_VERSION="$(nenv-version-name)"
fi

if [ "$NODE_VERSION" = "system" ]; then
    NODE_PATH="$(nenv-which node)"
    echo "${NODE_PATH%/*}"
    exit
fi

NENV_PREFIX_PATH="${NENV_ROOT}/versions/${NODE_VERSION}"
if [ ! -d "$NENV_PREFIX_PATH" ]; then
    echo "nenv: version \`${NODE_VERSION}' not installed" >&2
    exit 1
fi

echo "$NENV_PREFIX_PATH"
