#!/usr/bin/env bash
#-*- mode: shell-script; coding: utf-8; -*-
set -e
[[ -n $NENV_DEBUG ]] && set -x

NODE_VERSION="$1"
NODE_VERSION_FILE="${NENV_ROOT}/version"

case "$NODE_VERSION" in
    "" | "-h" | "--help" )
        echo "usage: nenv "${0/*nenv-/}" COMMAND [arg1 arg2...]" >&2
        exit 1
        ;;
    --command-help )
        echo $(command ls ${NENV_ROOT}/versions/)
        ;;
    "" )
        nenv-version-file "read" "$NODE_VERSION_FILE" ||
        nenv-version-file "read" "${NENV_ROOT}/global" ||
        nenv-version-file "read" "${NENV_ROOT}/default" ||
        echo system
        ;;
    * )
        nenv-version-file "write" "$NODE_VERSION_FILE" "$NODE_VERSION"
esac
