#!/usr/bin/env bash
# Summary: Show the current Node version
set -e
[ -n "$NENV_DEBUG" ] && set -x

if [ -z "$NENV_VERSION" ]; then
  NENV_VERSION_FILE="$(nenv-version-file)"
  NENV_VERSION="$(nenv-version-file-read "$NENV_VERSION_FILE" || true)"
fi

if [ -z "$NENV_VERSION" ] || [ "$NENV_VERSION" = "system" ]; then
  echo "system"
  exit
fi

version_exists() {
  local version="$1"
  [ -d "${NENV_ROOT}/versions/${version}" ]
}

if version_exists "$NENV_VERSION"; then
  echo "$NENV_VERSION"
elif version_exists "${NENV_VERSION#node-}"; then
  { echo "warning: ignoring extraneous \`node-' prefix in version \`${NENV_VERSION}'"
    echo "         (set by $(nenv-version-origin))"
  } >&2
  echo "${NENV_VERSION#node-}"
else
  echo "nenv: version \`$NENV_VERSION' is not installed" >&2
  exit 1
fi
